// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAko91_cJtcfvtKQT139gKspbo8CMxzaXE',
    appId: '1:997044681862:web:b9f849a0a62f5ee65de507',
    messagingSenderId: '997044681862',
    projectId: 'game-2f3f8',
    authDomain: 'game-2f3f8.firebaseapp.com',
    storageBucket: 'game-2f3f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDErseuS8aK2wa51fUfHlXhPdR_Hi6O0lg',
    appId: '1:997044681862:android:391f334b3ee2ca215de507',
    messagingSenderId: '997044681862',
    projectId: 'game-2f3f8',
    storageBucket: 'game-2f3f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvHIdyLvrfSSJRPLwUql768g3XSRnQoUo',
    appId: '1:997044681862:ios:f39b7f6deea4b42a5de507',
    messagingSenderId: '997044681862',
    projectId: 'game-2f3f8',
    storageBucket: 'game-2f3f8.appspot.com',
    iosClientId: '997044681862-s47728n55cj6ga62unefbpi8o8lvur0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvHIdyLvrfSSJRPLwUql768g3XSRnQoUo',
    appId: '1:997044681862:ios:f39b7f6deea4b42a5de507',
    messagingSenderId: '997044681862',
    projectId: 'game-2f3f8',
    storageBucket: 'game-2f3f8.appspot.com',
    iosClientId: '997044681862-s47728n55cj6ga62unefbpi8o8lvur0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.game',
  );
}
